export const products = [
    // Beds (3 items)
    {
        name: "Modern Bed",
        image: "/images/beds/bed1.webp",
        category: "beds",
        description: "A modern and comfortable bed with a minimalist design.",
        price: 500,
        percentage: 0,
        countInStock: 3,
        rating: 4.5,
    },
    {
        name: "Classic Bed",
        image: "/images/beds/bed2.webp",
        category: "beds",
        description:
            "A classic bed frame that offers a timeless look to any bedroom.",
        price: 450,
        percentage: 15,
        countInStock: 2,
        rating: 4.2,
    },
    {
        name: "Luxury Bed",
        image: "/images/beds/bed3.webp",
        category: "beds",
        description:
            "A luxurious bed with premium materials for ultimate comfort.",
        price: 800,
        percentage: 0,
        countInStock: 1,
        rating: 4.8,
    },

    // Chairs (7 items)
    {
        name: "Dining Chair",
        image: "/images/chairs/chair1.webp",
        category: "chairs",
        description: "A sturdy dining chair with a comfortable cushion.",
        price: 120,
        percentage: 50,
        countInStock: 10,
        rating: 4.3,
    },
    {
        name: "Office Chair",
        image: "/images/chairs/chair2.webp",
        category: "chairs",
        description: "An ergonomic office chair designed for all-day comfort.",
        price: 200,
        percentage: 0,
        countInStock: 5,
        rating: 4.7,
    },
    {
        name: "Lounge Chair",
        image: "/images/chairs/chair3.webp",
        category: "chairs",
        description:
            "A stylish lounge chair that adds a modern touch to any room.",
        price: 180,
        percentage: 0,
        countInStock: 3,
        rating: 4.5,
    },
    {
        name: "Recliner Chair",
        image: "/images/chairs/chair4.webp",
        category: "chairs",
        description:
            "A comfortable recliner with adjustable seating positions.",
        price: 350,
        percentage: 46,
        countInStock: 4,
        rating: 4.6,
    },
    {
        name: "Wooden Chair",
        image: "/images/chairs/chair5.webp",
        category: "chairs",
        description: "A classic wooden chair with a polished finish.",
        price: 750,
        percentage: 70,
        countInStock: 15,
        rating: 4.0,
    },
    {
        name: "Outdoor Chair",
        image: "/images/chairs/chair6.webp",
        category: "chairs",
        description: "A weather-resistant chair perfect for outdoor settings.",
        price: 295,
        percentage: 0,
        countInStock: 6,
        rating: 4.2,
    },
    {
        name: "Folding Chair",
        image: "/images/chairs/chair7.webp",
        category: "chairs",
        description: "A portable folding chair that’s easy to store and use.",
        price: 60,
        percentage: 16,
        countInStock: 8,
        rating: 4.1,
    },

    // Desks (5 items)
    {
        name: "Office Desk",
        image: "/images/desks/desk1.webp",
        category: "desks",
        description: "A spacious office desk with drawers for storage.",
        price: 300,
        percentage: 0,
        countInStock: 5,
        rating: 4.4,
    },
    {
        name: "Standing Desk",
        image: "/images/desks/desk2.webp",
        category: "desks",
        description: "A height-adjustable standing desk for healthier working.",
        price: 450,
        percentage: 0,
        countInStock: 2,
        rating: 4.6,
    },
    {
        name: "Gaming Desk",
        image: "/images/desks/desk3.webp",
        category: "desks",
        description:
            "A desk designed for gaming setups with cable management features.",
        price: 820,
        percentage: 80,
        countInStock: 3,
        rating: 4.8,
    },
    {
        name: "Writing Desk",
        image: "/images/desks/desk4.webp",
        category: "desks",
        description: "A compact writing desk ideal for small spaces.",
        price: 150,
        percentage: 0,
        countInStock: 6,
        rating: 4.2,
    },
    {
        name: "Executive Desk",
        image: "/images/desks/desk5.webp",
        category: "desks",
        description: "An elegant executive desk with a luxurious finish.",
        price: 600,
        percentage: 15,
        countInStock: 1,
        rating: 4.9,
    },

    // Sofas (5 items)
    {
        name: "Leather Sofa",
        image: "/images/sofas/sofa1.webp",
        category: "sofas",
        description:
            "A stylish leather sofa that adds sophistication to any room.",
        price: 1500,
        percentage: 60,
        countInStock: 5,
        rating: 4.5,
    },
    {
        name: "Sectional Sofa",
        image: "/images/sofas/sofa2.webp",
        category: "sofas",
        description: "A large sectional sofa perfect for family gatherings.",
        price: 900,
        percentage: 12,
        countInStock: 2,
        rating: 4.7,
    },
    {
        name: "Loveseat Sofa",
        image: "/images/sofas/sofa3.webp",
        category: "sofas",
        description: "A cozy loveseat sofa, ideal for small living rooms.",
        price: 450,
        percentage: 0,
        countInStock: 4,
        rating: 4.3,
    },
    {
        name: "Convertible Sofa",
        image: "/images/sofas/sofa4.webp",
        category: "sofas",
        description: "A versatile convertible sofa that doubles as a bed.",
        price: 650,
        percentage: 10,
        countInStock: 3,
        rating: 4.6,
    },
    {
        name: "Fabric Sofa",
        image: "/images/sofas/sofa5.webp",
        category: "sofas",
        description:
            "A soft fabric sofa with removable covers for easy cleaning.",
        price: 500,
        percentage: 0,
        countInStock: 3,
        rating: 4.4,
    },

    // Tables (4 items)
    {
        name: "Dining Table",
        image: "/images/tables/table1.webp",
        category: "tables",
        description: "A modern dining table perfect for family meals.",
        price: 400,
        percentage: 0,
        countInStock: 4,
        rating: 4.3,
    },
    {
        name: "Coffee Table",
        image: "/images/tables/table2.webp",
        category: "tables",
        description: "A stylish coffee table that enhances any living space.",
        price: 150,
        percentage: 5,
        countInStock: 6,
        rating: 4.1,
    },
    {
        name: "Console Table",
        image: "/images/tables/table3.webp",
        category: "tables",
        description: "A narrow console table ideal for hallways and entryways.",
        price: 220,
        percentage: 0,
        countInStock: 3,
        rating: 4.2,
    },
    {
        name: "End Table",
        image: "/images/tables/table4.webp",
        category: "tables",
        description: "A compact end table that fits well beside any sofa.",
        price: 100,
        percentage: 0,
        countInStock: 7,
        rating: 4.0,
    },
];
